### Consider the below code to answer further questions:
```
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```
**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

Yes, there is a difference in the data type between the list_ variable and the array_list variable. The list_ variable is a Python list, while the array_list variable is a NumPy array.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [2]:
for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [3]:
# Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list. When you specify dtype=int in np.array, it will convert the elements of the list to integers.

array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_ variable:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list variable:")
for element in array_list:
    print(type(element))


Data types of elements in list_ variable:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list variable:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Consider the below code to answer further questions:
```
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```
**Q4. Write a code to find the following characteristics of variable, num_array:**
(i) shape
(ii) size

In [4]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
matrix = np.zeros(shape=(3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
matrix = np.identity(n=5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
